### PR TITLE
Split run script into modules

### PR DESCRIPTION
**Pull request by edwharbison**

### CODE REVIEW

**Comment by timothymurphy** [comment]
Please, if you are making changes to files try and make their coverage better than it was. We are having issues with figuring out how to test __main__ files, but if you are pulling parts of it out into different scripts, those should be coverable. If it works on top of other calls, assert that those calls are being made. If you want to make it covered at a higher level, python should be able to run command line level calls and assert a changed state. Make sure to run `pytest --cov=src tests/` and any new files added should have complete coverage. I am still figuring out myself how to see what statements are not covered, I'll keep everyone updated on that.

**Comment by timothymurphy** [comment]
Try using 'pytest --cov-report term-missing --cov=src tests/' to find what lines are not covered, or what pytest coverage wants to have covered.

**Comment by edwharbison** [comment]
Implemented tests for anything that is testable to my knowledge (and StackOverflow questions seem to agree).  Some things say they aren't tested but they clearly are, so I don't really know what to say about that.  Current coverage is at 82% with 120 tests.

**Comment by timothymurphy** [comment]
Looking into why coverage isn't working for those tests @edwharbison

**Comment by bjcoleman** [comment]
Come see me to understand why coverage is not happening.

**Comment by edwharbison** [comment]
As per request, `_core/__main__.py` no longer exists, meaning run scripts are slightly different.  Use `mirrulations_client` for client and `mirrulations_server` for server with `--config` as per usual.  Tests for the remaining `__main__.py`s are 100%, raising coverage to 84% overall.

**Pull request merged**
